package it.uniroma2.RunTeam.Sudoku.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.ui.graphics.Color

fun jungleLightColorScheme(
    primary: Color = Color(0xFF006B3C),
    onPrimary: Color = Color(0xFFFFFFFF),
    primaryContainer: Color = Color(0xFF93F7C1),
    onPrimaryContainer: Color = Color(0xFF00210F),
    inversePrimary: Color = Color(0xFF4ADE9E),
    secondary: Color = Color(0xFF336951),
    onSecondary: Color = Color(0xFFFFFFFF),
    secondaryContainer: Color = Color(0xFFC5EDD9),
    onSecondaryContainer: Color = Color(0xFF002114),
    tertiary: Color = Color(0xFF1E6A3F),
    onTertiary: Color = Color(0xFFFFFFFF),
    tertiaryContainer: Color = Color(0xFF9EF3C9),
    onTertiaryContainer: Color = Color(0xFF002113),
    background: Color = Color(0xFFF2F9F3),
    onBackground: Color = Color(0xFF102017),
    surface: Color = Color(0xFFFBFBFB),
    onSurface: Color = Color(0xFF102018),
    surfaceVariant: Color = Color(0xFFDAE5E1),
    onSurfaceVariant: Color = Color(0xFF3F4945),
    surfaceTint: Color = primary,
    inverseSurface: Color = Color(0xFF20332A),
    inverseOnSurface: Color = Color(0xFFECF2ED),
    error: Color = Color(0xFFBA1A1A),
    onError: Color = Color(0xFFFFFFFF),
    errorContainer: Color = Color(0xFFFFDAD4),
    onErrorContainer: Color = Color(0xFF410002),
    outline: Color = Color(0xFF6F7975),
    outlineVariant: Color = Color(0xFFBFC9C4),
    scrim: Color = Color(0xFF000000),
    surfaceBright: Color = Color(0xFFFBFBFB),
    surfaceContainer: Color = Color(0xFFEBF3EE),
    surfaceContainerHigh: Color = Color(0xFFDAE3DF),
    surfaceContainerHighest: Color = Color(0xFFCAD3CF),
    surfaceContainerLow: Color = Color(0xFFF1F9F3),
    surfaceContainerLowest: Color = Color(0xFFFFFFFF),
    surfaceDim: Color = Color(0xFFD9E0DB),
): ColorScheme =
    ColorScheme(
        primary = primary, onPrimary = onPrimary, primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer, inversePrimary = inversePrimary,
        secondary = secondary, onSecondary = onSecondary, secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer, tertiary = tertiary, onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer, onTertiaryContainer = onTertiaryContainer,
        background = background, onBackground = onBackground, surface = surface,
        onSurface = onSurface, surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint, inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface, error = error, onError = onError,
        errorContainer = errorContainer, onErrorContainer = onErrorContainer,
        outline = outline, outlineVariant = outlineVariant, scrim = scrim,
        surfaceBright = surfaceBright, surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh, surfaceContainerHighest = surfaceContainerHighest,
        surfaceContainerLow = surfaceContainerLow, surfaceContainerLowest = surfaceContainerLowest,
        surfaceDim = surfaceDim,
    )

fun oceanLightColorScheme(
    primary: Color = Color(0xFF005B9A),
    onPrimary: Color = Color(0xFFFFFFFF),
    primaryContainer: Color = Color(0xFF5FB8FF),
    onPrimaryContainer: Color = Color(0xFF001B33),
    inversePrimary: Color = Color(0xFF5FB8FF),
    secondary: Color = Color(0xFF006497),
    onSecondary: Color = Color(0xFFFFFFFF),
    secondaryContainer: Color = Color(0xFFCCE8FF),
    onSecondaryContainer: Color = Color(0xFF001E2E),
    tertiary: Color = Color(0xFF00527E),
    onTertiary: Color = Color(0xFFFFFFFF),
    tertiaryContainer: Color = Color(0xFFBCE4FF),
    onTertiaryContainer: Color = Color(0xFF001A29),
    background: Color = Color(0xFFF3F9FF),
    onBackground: Color = Color(0xFF101E27),
    surface: Color = Color(0xFFFFFFFF),
    onSurface: Color = Color(0xFF101F27),
    surfaceVariant: Color = Color(0xFFD9E3EB),
    onSurfaceVariant: Color = Color(0xFF40484C),
    surfaceTint: Color = primary,
    inverseSurface: Color = Color(0xFF1F3139),
    inverseOnSurface: Color = Color(0xFFEBF1F5),
    error: Color = Color(0xFFBA1A1A),
    onError: Color = Color(0xFFFFFFFF),
    errorContainer: Color = Color(0xFFFFDAD4),
    onErrorContainer: Color = Color(0xFF410002),
    outline: Color = Color(0xFF70797F),
    outlineVariant: Color = Color(0xFFBFC8CF),
    scrim: Color = Color(0xFF000000),
    surfaceBright: Color = Color(0xFFFBFBFB),
    surfaceContainer: Color = Color(0xFFECF3F7),
    surfaceContainerHigh: Color = Color(0xFFDCE3E9),
    surfaceContainerHighest: Color = Color(0xFFCBD3DA),
    surfaceContainerLow: Color = Color(0xFFF1F7FB),
    surfaceContainerLowest: Color = Color(0xFFFFFFFF),
    surfaceDim: Color = Color(0xFFD9E0E5),
): ColorScheme =
    ColorScheme(
        primary = primary, onPrimary = onPrimary, primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer, inversePrimary = inversePrimary,
        secondary = secondary, onSecondary = onSecondary, secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer, tertiary = tertiary, onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer, onTertiaryContainer = onTertiaryContainer,
        background = background, onBackground = onBackground, surface = surface,
        onSurface = onSurface, surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint, inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface, error = error, onError = onError,
        errorContainer = errorContainer, onErrorContainer = onErrorContainer,
        outline = outline, outlineVariant = outlineVariant, scrim = scrim,
        surfaceBright = surfaceBright, surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh, surfaceContainerHighest = surfaceContainerHighest,
        surfaceContainerLow = surfaceContainerLow, surfaceContainerLowest = surfaceContainerLowest,
        surfaceDim = surfaceDim,
    )

fun auroraLightColorScheme(
    primary: Color = Color(0xFF6A5AF9),
    onPrimary: Color = Color(0xFFFFFFFF),
    primaryContainer: Color = Color(0x336A5AF9),
    onPrimaryContainer: Color = Color(0xFF0A0044),
    inversePrimary: Color = Color(0xFF9C93FF),
    secondary: Color = Color(0xFF3FB8AF),
    onSecondary: Color = Color(0xFF002928),
    secondaryContainer: Color = Color(0x333FB8AF),
    onSecondaryContainer: Color = Color(0xFF001414),
    tertiary: Color = Color(0xFFB93CE3),
    onTertiary: Color = Color(0xFFFFFFFF),
    tertiaryContainer: Color = Color(0x33B93CE3),
    onTertiaryContainer: Color = Color(0xFF1E002C),
    background: Color = Color(0xFF12131C),
    onBackground: Color = Color(0xFFE3E3E9),
    surface: Color = Color(0xFF1A1B27),
    onSurface: Color = Color(0xFFE3E3E9),
    surfaceVariant: Color = Color(0xFF232535),
    onSurfaceVariant: Color = Color(0xFFB0B3C5),
    surfaceTint: Color = primary,
    inverseSurface: Color = Color(0xFFECEDF4),
    inverseOnSurface: Color = Color(0xFF222329),
    error: Color = Color(0xFFBA1A1A),
    onError: Color = Color(0xFFFFFFFF),
    errorContainer: Color = Color(0x33BA1A1A),
    onErrorContainer: Color = Color(0xFF410002),
    outline: Color = Color(0xFF4A4C57),
    outlineVariant: Color = Color(0xFF323445),
    scrim: Color = Color(0x66000000),
    surfaceBright: Color = Color(0xFF2A2B3A),
    surfaceContainer: Color = Color(0xFF1E1F2C),
    surfaceContainerHigh: Color = Color(0xFF2B2C3C),
    surfaceContainerHighest: Color = Color(0xFF373849),
    surfaceContainerLow: Color = Color(0xFF1C1C27),
    surfaceContainerLowest: Color = Color(0xFF12131C),
    surfaceDim: Color = Color(0xFF0F0F16),
): ColorScheme =
    ColorScheme(
        primary = primary, onPrimary = onPrimary, primaryContainer = primaryContainer,
        onPrimaryContainer = onPrimaryContainer, inversePrimary = inversePrimary,
        secondary = secondary, onSecondary = onSecondary, secondaryContainer = secondaryContainer,
        onSecondaryContainer = onSecondaryContainer, tertiary = tertiary, onTertiary = onTertiary,
        tertiaryContainer = tertiaryContainer, onTertiaryContainer = onTertiaryContainer,
        background = background, onBackground = onBackground, surface = surface,
        onSurface = onSurface, surfaceVariant = surfaceVariant, onSurfaceVariant = onSurfaceVariant,
        surfaceTint = surfaceTint, inverseSurface = inverseSurface,
        inverseOnSurface = inverseOnSurface, error = error, onError = onError,
        errorContainer = errorContainer, onErrorContainer = onErrorContainer,
        outline = outline, outlineVariant = outlineVariant, scrim = scrim,
        surfaceBright = surfaceBright, surfaceContainer = surfaceContainer,
        surfaceContainerHigh = surfaceContainerHigh, surfaceContainerHighest = surfaceContainerHighest,
        surfaceContainerLow = surfaceContainerLow, surfaceContainerLowest = surfaceContainerLowest,
        surfaceDim = surfaceDim,
    )


